### ISSUE TITLE
🐛 [Addon name] <title>unknown filesystem type 'ntfs3'

### ISSUE THREAD

**Issue by ufacek** [dianlight/hassio-addons#186] opened 2023-12-10 13:27 UTC
### Addon

SambaNAS

### Description

Generic x86-64
Core 2023.12.1
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231208.2
H30-00 Desktop (Lenovo) - Type 90C2 

I've tried to mount windows disk using Samba NAS and got the error:
[14:01:25] INFO: Mounting disks:

	MEDIA
---------------------------------------------------
[14:01:25] WARNING: Your MEDIA is ntfs. This is an EXPERIMENTAL support
mount: /mnt/MEDIA: unknown filesystem type 'ntfs3'.
       dmesg(1) may have more information after failed mount system call.
[14:01:25] WARNING: Fail to mount MEDIA!

I would like to ask for help, how to make it work without formatting to ext4 :)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
MEDIA
---------------------------------------------------
---------------------------------------------------
[14:01:25] INFO: Mounting disks:

	MEDIA
---------------------------------------------------
[14:01:25] WARNING: Your MEDIA is ntfs. This is an EXPERIMENTAL support
mount: /mnt/MEDIA: unknown filesystem type 'ntfs3'.
       dmesg(1) may have more information after failed mount system call.
[14:01:25] WARNING: Fail to mount MEDIA!
s6-rc: info: service init-automount successfully started
s6-rc: info: service init-smartd: starting
s6-rc: info: service init-samba: starting
s6-rc: info: service hd-idle: starting
s6-rc: info: service hd-idle successfully started
[14:01:26] INFO: Enabling S.M.A.R.T for /dev/sda
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.1.63-haos] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

[14:01:26] INFO: Hostname: homeassistant
=== START OF ENABLE/DISABLE COMMANDS SECTION ===
SMART Enabled.
SMART Attribute Autosave Enabled.
SMART Automatic Timers not supported

SMART Enable Automatic Offline failed: scsi error badly formed scsi parameters


[14:01:26] INFO: Enabling S.M.A.R.T for /dev/sdb
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.1.63-haos] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

[14:01:26] INFO: Interfaces: enp2s0 
[14:01:26] INFO: Docker Interface: hassio 172.30.32.0/23
=== START OF ENABLE/DISABLE COMMANDS SECTION ===
SMART Enabled.
SMART Attribute Autosave Enabled.
SMART Automatic Offline Testing Enabled every four hours.

s6-rc: info: service init-smartd successfully started
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user homeassistant.
---------------------------------------------------
[14:01:27] INFO: Exposed Disks Summary:
[config]                path = /homeassistant # TM:false#
[addons]                path = /addons # TM:false#
[ssl]                   path = /ssl # TM:false#
[share]                 path = /share # TM:false#
[backup]                path = /backup # TM:false#
[media]                 path = /media # TM:false#
[addon_configs]         path = /addon_configs # TM:false#
---------------------------------------------------
s6-rc: info: service init-samba successfully started
s6-rc: info: service init-mqtt: starting
s6-rc: info: service wsdd: starting
s6-rc: info: service smbd: starting
s6-rc: info: service nmbd: starting
s6-rc: info: service avahi: starting
s6-rc: info: service wsdd successfully started
s6-rc: info: service smbd successfully started
s6-rc: info: service avahi successfully started
s6-rc: info: service nmbd successfully started
s6-rc: info: service cifs-supervisor-mount: starting
nmbd version 4.18.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2023
s6-rc: info: service cifs-supervisor-mount successfully started
[14:01:27] INFO: Starting the AVAHI for homeassistant...
Waiting for daemon ...
smbd version 4.18.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2023
INFO: Profiling support unavailable in this build.
[14:01:27] INFO: MQTT support not enabled in config
s6-rc: info: service init-mqtt successfully started
s6-rc: info: service mqtt-disk-handler: starting
s6-rc: info: service mqtt-disk-handler successfully started
s6-rc: info: service mqtt-handler: starting
s6-rc: info: service mqtt-handler successfully started
s6-rc: info: service legacy-services: starting
[14:01:27] INFO: Starting the wsdd daemon for WORKGROUP/homeassistant...
s6-rc: info: service legacy-services successfully started
[14:01:27] INFO: Interfaces: -i enp2s0 
2023-12-10 14:01:28,502:wsdd INFO(pid 335): using pre-defined UUID cb6a33a0-b841-531d-a34e-09ecec492eb1
2023-12-10 14:01:28,506:wsdd INFO(pid 335): joined multicast group 239.255.255.250 on 192.168.68.121%enp2s0
2023-12-10 14:01:28,511:wsdd INFO(pid 335): scheduling Hello message via enp2s0 to 239.255.255.250%enp2s0
2023-12-10 14:01:28,574:wsdd INFO(pid 335): joined multicast group [ff02::c] on fe80::5418:bc04:6c8b:8862%enp2s0
2023-12-10 14:01:28,575:wsdd INFO(pid 335): scheduling Hello message via enp2s0 to ff02::c%enp2s0
2023-12-10 14:01:28,631:wsdd INFO(pid 335): 192.168.68.116 - - "POST /cb6a33a0-b841-531d-a34e-09ecec492eb1 HTTP/1.1" 200 -
2023-12-10 14:01:28,643:wsdd INFO(pid 335): fe80::b3b7:1dd3:853b:2e21 - - "POST /cb6a33a0-b841-531d-a34e-09ecec492eb1 HTTP/1.1" 200 -
*****

Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 192.168.68.121
```

### Addon Config

```bash
workgroup: WORKGROUP
username: *
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 169.254.0.0/16
  - fe80::/10
automount: false
moredisks:
  - MEDIA
mountoptions:
  - nosuid
  - relatime
  - noexec
available_disks_log: true
medialibrary:
  enable: false
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
recyle_bin_enabled: false
wsdd2: false
mqtt_use_legacy_entities: false
autodiscovery: {}
other_users: []
acl: []
interfaces: []
password: *
```

### Architecture

other

### OS

HaOS

**Comment by dianlight** [comment] 2023-12-11 07:44
It is not a bug. Arch x86-64 don't have ntfs3 fs module compiled.
You should look on hassos issue to check how resolve.

**Comment by dianlight** [comment] 2023-12-11 07:48
Duplicate of #160

**Closed** 2023-12-11 07:48 UTC
Labels: duplicate, wontfix, [ SambaNas ]
