### ISSUE TITLE
No Disk with labels

### ISSUE THREAD

**Issue by hsellik** [dianlight/hassio-addons#136] opened 2023-02-18 15:36 UTC
Hi

Just formatted an external M.2 SSD. It initially worked, but overnight, the disk was gone and the plugin logs say "No Disk with labels." when restarting.

Formatted the drive to ext4, added gpt label and partition label. 

Are there any good ways to see if the SSD is even recognized? The only ways I could come up with are the ones below and I'm not sure how to debug this further. 
```
ha os datadisk list
devices:
- /dev/sda
```

 I can also see `sda` under all hardware. It's an m.2 ssd connected through an m.2 -> usb adapter:
```
sda
/dev/disk/by-id/usb-JMicron_Tech_DD564198838EA-0:0
Subsystem:
block
Device path:
/dev/sda
ID:
/dev/disk/by-id/usb-JMicron_Tech_DD564198838EA-0:0
Attributes:
DEVLINKS: >-
  /dev/disk/by-id/usb-JMicron_Tech_DD564198838EA-0:0
  /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0
DEVNAME: /dev/sda
DEVPATH: >-
  /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/host0/target0:0:0/0:0:0:0/block/sda
DEVTYPE: disk
DISKSEQ: '29'
ID_BUS: usb
ID_INSTANCE: '0:0'
ID_MODEL: Tech
ID_MODEL_ENC: Tech\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_MODEL_ID: a583
ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0
ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_2_1_0-scsi-0_0_0_0
ID_REVISION: '0213'
ID_SERIAL: JMicron_Tech_DD564198838EA-0:0
ID_SERIAL_SHORT: DD564198838EA
ID_TYPE: disk
ID_USB_DRIVER: uas
ID_USB_INTERFACES: ':080650:080662:'
ID_USB_INTERFACE_NUM: '00'
ID_VENDOR: JMicron
ID_VENDOR_ENC: JMicron\x20
ID_VENDOR_ID: 152d
MAJOR: '8'
MINOR: '0'
SUBSYSTEM: block
TAGS: ':systemd:'
USEC_INITIALIZED: '375773079'
```

Logs:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Samba NAS
 Expose Home Assistant disc with SMB/CIFS
-----------------------------------------------------------
 Add-on version: 10.0.0-nas8
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.2.5
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
[17:07:35] INFO: Protection Mode is false
[17:07:35] INFO: MoreDisk or Automount option found!
---------------------------------------------------
Supported fs: ext3 ext2 ext4 squashfs vfat msdos f2fs fuseblk ntfs3 exfat btrfs xfs
Supported fusefs: 
---------------------------------------------------
[17:07:35] INFO: MediaLibrary disabled in config. Disk are mounted only for this addon!
---------------------------------------------------
[17:07:35] INFO: No Disk with labels.
---------------------------------------------------
[17:07:36] INFO: MoreDisks to mount:
	NAS
[17:07:36] WARNING: Disk with label NAS not found.
s6-rc: info: service init-automount successfully started
s6-rc: info: service init-smartd: starting
s6-rc: info: service init-samba: starting
s6-rc: info: service hd-idle: starting
s6-rc: info: service hd-idle successfully started
s6-rc: info: service init-smartd successfully started
[17:07:37] INFO: Hostname: homeassistant
[17:07:37] INFO: Interfaces: eth0 wlan0 
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user homeassistant.
---------------------------------------------------
[17:07:38] INFO: Exposed Disks Summary:
[config]                path = /config
[addons]                path = /addons
[ssl]                   path = /ssl
[share]                 path = /share
[backup]                path = /backup
[media]                 path = /media
---------------------------------------------------
s6-rc: info: service init-samba successfully started
s6-rc: info: service init-mqtt: starting
s6-rc: info: service wsdd: starting
s6-rc: info: service smbd: starting
s6-rc: info: service nmbd: starting
s6-rc: info: service avahi: starting
[17:07:39] INFO: Starting the AVAHI for homeassistant...
Waiting for daemon ...
[17:07:39] INFO: Starting the wsdd daemon for WORKGROUP/homeassistant...
[17:07:39] INFO: Interfaces: -i eth0 -i wlan0 
2023-02-18 17:07:40,320:wsdd INFO(pid 306): using pre-defined UUID cb6a33a0-b841-531d-a34e-09ecec492eb1
2023-02-18 17:07:40,325:wsdd INFO(pid 306): joined multicast group ('239.255.255.250', 3702) on 192.168.3.12%eth0
2023-02-18 17:07:40,339:wsdd INFO(pid 306): scheduling Hello message via eth0 to ('239.255.255.250', 3702)
2023-02-18 17:07:40,376:wsdd INFO(pid 306): joined multicast group ('ff02::c', 3702, 22364, 2) on fe80::1665:bc64:5be3:256f%eth0
2023-02-18 17:07:40,378:wsdd INFO(pid 306): scheduling Hello message via eth0 to ('ff02::c', 3702, 22364, 2)
s6-rc: info: service nmbd successfully started
s6-rc: info: service wsdd successfully started
s6-rc: info: service smbd successfully started
s6-rc: info: service avahi successfully started
s6-rc: info: service init-mqtt successfully started
s6-rc: info: service mqtt-disk-handler: starting
s6-rc: info: service mqtt-disk-handler successfully started
s6-rc: info: service mqtt-handler: starting
s6-rc: info: service mqtt-handler successfully started
s6-rc: info: service legacy-services: starting
[17:07:41] INFO: Starting the MQTT daemon for disks info...
[17:07:41] INFO: Starting the MQTT daemon for partitions info...
s6-rc: info: service legacy-services successfully started
[17:07:41] INFO: MQTT integration
nmbd version 4.16.8 started.
smbd version 4.16.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2022
Copyright Andrew Tridgell and the Samba Team 1992-2022
INFO: Profiling support unavailable in this build.
```

**Comment by dianlight** [comment] 2023-02-20 09:07
/dev/sda is a disk but you need to mount a partition ( tipically /dev/sda1).
I suggest you to see if in HA under Settings--> System--> Hardware --> All Hardware you see the partitions.
A label on a partition can't go away without a hw or software failure.

If you find only the partition id you can try to mount by id (`moredisks` with format `id:.....`)



L.

**Comment by hsellik** [comment] 2023-02-20 11:25
Took the SSD out, reformatted it, and added labels again. I don't suspect a hardware failure at this point yet. For some reason, ha os doesn't recognize the partition?

All I can see in all hardware are partitions for what I presume is the SD card:
![image](https://user-images.githubusercontent.com/16798824/220092728-f537205c-ff6b-4646-a278-bd88177d5e25.png)

**Comment by dianlight** [comment] 2023-02-20 14:21
I interpret "Took the SSD out" to mean you unplugged the USB drive not that you took the M.2 out of the USB case.

If that's correct and you were able to reformat the drive there is probably no hw problem.

At this point:
- Check the power supply. 90% of such problems are caused by an RPi power issue. Add the RPiPower sensor and check that everything is OK. [Link](https://www.home-assistant.io/integrations/rpi_power/). 
- Is the disk connected to the RPI's USB3 or USB2 port? If it's on 3 try moving it to 2; if it goes your case is not fully supported by the Rpi (go to the next point)
- Try to upgrade the firmware of the RPi. [Link](https://www.raspberrypi.com/documentation/computers/os.html)
- Is the partition table GPT or MBA?  If in doubt, re-partition the M.2 in GPT.

L.

**Comment by hsellik** [comment] 2023-02-20 14:33
Exactly, in my case, it meant unplugging the USB drive. :)

The power sensor shows OK.

I'll see if moving to a USB2 port or firmware upgrade have any effects.

**Comment by hsellik** [comment] 2023-02-22 08:24
Upgraded firmware to the latest stable version. Tried USB2 and USB3 ports, but still no luck. :cry:

**Comment by dianlight** [comment] 2023-02-22 09:25
It's more of a linux kernel theme than HA. You should see the system logs when you connect the disk.
Just out of curiosity; what operating system did you use to make partitions and format the partition? You're not using diskencryption like bitlocker or similar right?

If you can, try to connect the disk to a PC with Linux (even a Live version is fine) and see if the partitions are seen or not.

**Comment by hsellik** [comment] 2023-02-22 09:44
Created partitions with Ubuntu using GParted. No encryption. Used GPT and ext4. Seems to be recognized just fine when inserting it into the laptop.

One weird thing I noticed was that on the first try:
* NAS addon was working just fine, left it overnight
* Next day it didn't work
* The disk was like 30GB full before I reformatted the disk again (did not veto any files since I couldn't access NAS through Windows when I did)

No changes to the Home Assistant system were made, but it just didn't work anymore.

I'll try to find and inspect the system logs when connecting the disk. I'll also try to see if there are any other useful commands that I can use to determine whether the Home Assistant OS even recognizes the SSD connected to the USB adapter. Seems that the adapter itself is recognized.

Did not include the

**Comment by dianlight** [comment] 2023-02-22 11:14
As I wrote above a drive doesn't disappear overnight without a hardware or software failure.
The strange thing in your case is that the error persists but the disk seems to work, which excludes a software error ( persists ) and hardware ( works if connected to another system ).

The idea that I got is that there has been an error or sw or hw that has corrupted the partition table and this leads the linux kernel to ignore the partitions. Windows is much trickier than linux and doesn't do consistency checks (paradoxically for example in Windows you can create 4T partitions on 2T disks and it doesn't realize it! - trick used by many dishonest hardware sellers to sell you a disk but deliver you a minor capacity disk.. OT )

The best thing to do is try again with Ubuntu to see if by connecting the disk you see it and you see the partition. If you are not interested in the data, even if you see the partition I would say redo the partition table. Also do a S.M.A.R.T test to see that there are no problems is usefull.

If it can connect to the host of your HA installation you can try looking in /dev/disk/by-id/
what appears.
Your drive is called `usb-JMicron_Tech_DD564198838EA-0:0` but if there are partitions there should also be a `usb-JMicron_Tech_DD564198838EA-0:xx` where xx is from 1 to n and are the detected partitions.

In your case i should be:
```
$ ls -l /dev/disk/by-id/
lrwxrwxrwx 1 root root 10 May 27 23:31 usb-JMicron_Tech_DD564198838EA-0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 May 27 23:31 usb-JMicron_Tech_DD564198838EA-0:1 -> ../../sda1
```

Other usefull commands:

- `lsblk -f` 
- `blkid`

Usefull link: https://wiki.archlinux.org/title/persistent_block_device_naming


L.

**Comment by hsellik** [comment] 2023-02-23 06:53
It seems that other people are also experiencing trouble using USB - NVMe controllers and JMicron is especially notorious. 

In my case, it's JMS583 revision A3.
* Tried to add quirk to cmdline.txt : https://forums.raspberrypi.com/viewtopic.php?=278662 (didn't work)
* But people have also suggested other fixes such as changing usb_modeswitch.conf: https://forums.raspberrypi.com/viewtopic.php?t=310993 (have to see about that one)

Anyway, it's not really a problem with this addon, but really a more general problem with Raspberry Pi  + Home Assistant Operating System + JMicron controllers. I'll try to make a PR to the README of this project regarding some commands that helped during debugging and a general note about the NVME controllers.

Thank you for looking into this and helping out!

**Closed** 2023-05-02 10:30 UTC
Labels: To verify, [ SambaNas ], no-issue-activity

**Comment by hsellik** [comment] 2023-05-03 18:40
A little update. Tried updating the firmware and using a powered USB hub, didn't work, unfortunately. I'll try my luck with another NVME adapter.

Used the tool from here for the firmware upgrade: https://www.reddit.com/r/NewMaxx/comments/i5r5rb/jms583_209_firmware/

Probably going to try icy box which is suggested here: https://jamesachambers.com/new-raspberry-pi-4-bootloader-usb-network-boot-guide/
