### ISSUE TITLE
sleep: unbound variable

### ISSUE THREAD

**Issue by cokeman0** [dianlight/hassio-addons#152] opened 2023-06-19 16:37 UTC
I'm getting this in the log:

s6-rc: info: service init-mqtt successfully started
s6-rc: info: service mqtt-disk-handler: starting
s6-rc: info: service mqtt-disk-handler successfully started
s6-rc: info: service mqtt-handler: starting
s6-rc: info: service mqtt-handler successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
./run: line 144: sleep: unbound variable
./run: line 144: sleep: unbound variable

**Comment by dianlight** [comment] 2023-06-19 17:41
Duplicate of #151

**Closed by dianlight** 2023-06-19 17:41 UTC
